route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: abc@gmail.com
    from: from@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "from@gmail.com"
    auth_identity: "from@gmail.com"
    auth_password: "fromPassword"